### ISSUE TITLE
Retorno de la funcion insertion_sort

### ISSUE THREAD

**Issue by BetoC2** [BetoC2/PMD-002-pointers#1]
Profe, en las indicaciones de la función *insertion_sort* (las que están en inglés) nos pide que la función no regrese nada, pero en las indicaciones en español nos pide que regresemos el número de *swaps* que se hizo. ¿La dejamos sin retornar nada?

**Comment by DevCam** [comment]
Si, error de copy-paste, insertion sort no retorna nada
